<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5tuGP2Y' shared service.

return $this->privates['.service_locator.5tuGP2Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.5tuGP2Y.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.5tuGP2Y": it references class "App\\Entity\\Articles" but no such service exists.'],
    'categorie' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService.php', true],
], [
    'article' => 'App\\Entity\\Articles',
    'categorie' => 'App\\Repository\\CategoriesRepository',
]);
