<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d3fETTc' shared service.

return $this->privates['.service_locator.d3fETTc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articlesRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService.php', true],
], [
    'articlesRepository' => 'App\\Repository\\ArticlesRepository',
]);
