<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nLoTd6_' shared service.

return $this->privates['.service_locator.nLoTd6_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articles' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService.php', true],
    'categories' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService.php', true],
], [
    'articles' => 'App\\Repository\\ArticlesRepository',
    'categories' => 'App\\Repository\\CategoriesRepository',
]);
