<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Iti7riY' shared service.

return $this->privates['.service_locator.Iti7riY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticlesController::delete' => ['privates', '.service_locator.Ho7wU.E', 'get_ServiceLocator_Ho7wU_EService.php', true],
    'App\\Controller\\ArticlesController::edit' => ['privates', '.service_locator.Ho7wU.E', 'get_ServiceLocator_Ho7wU_EService.php', true],
    'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.d3fETTc', 'get_ServiceLocator_D3fETTcService.php', true],
    'App\\Controller\\ArticlesController::show' => ['privates', '.service_locator.5tuGP2Y', 'get_ServiceLocator_5tuGP2YService.php', true],
    'App\\Controller\\ContactController::index' => ['privates', '.service_locator.rXrRW6k', 'get_ServiceLocator_RXrRW6kService.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.nLoTd6_', 'get_ServiceLocator_NLoTd6Service.php', true],
    'App\\Controller\\HomeController::show' => ['privates', '.service_locator.5tuGP2Y', 'get_ServiceLocator_5tuGP2YService.php', true],
    'App\\Controller\\ArticlesController:delete' => ['privates', '.service_locator.Ho7wU.E', 'get_ServiceLocator_Ho7wU_EService.php', true],
    'App\\Controller\\ArticlesController:edit' => ['privates', '.service_locator.Ho7wU.E', 'get_ServiceLocator_Ho7wU_EService.php', true],
    'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.d3fETTc', 'get_ServiceLocator_D3fETTcService.php', true],
    'App\\Controller\\ArticlesController:show' => ['privates', '.service_locator.5tuGP2Y', 'get_ServiceLocator_5tuGP2YService.php', true],
    'App\\Controller\\ContactController:index' => ['privates', '.service_locator.rXrRW6k', 'get_ServiceLocator_RXrRW6kService.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.nLoTd6_', 'get_ServiceLocator_NLoTd6Service.php', true],
    'App\\Controller\\HomeController:show' => ['privates', '.service_locator.5tuGP2Y', 'get_ServiceLocator_5tuGP2YService.php', true],
], [
    'App\\Controller\\ArticlesController::delete' => '?',
    'App\\Controller\\ArticlesController::edit' => '?',
    'App\\Controller\\ArticlesController::index' => '?',
    'App\\Controller\\ArticlesController::show' => '?',
    'App\\Controller\\ContactController::index' => '?',
    'App\\Controller\\HomeController::index' => '?',
    'App\\Controller\\HomeController::show' => '?',
    'App\\Controller\\ArticlesController:delete' => '?',
    'App\\Controller\\ArticlesController:edit' => '?',
    'App\\Controller\\ArticlesController:index' => '?',
    'App\\Controller\\ArticlesController:show' => '?',
    'App\\Controller\\ContactController:index' => '?',
    'App\\Controller\\HomeController:index' => '?',
    'App\\Controller\\HomeController:show' => '?',
]);
