<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rXrRW6k' shared service.

return $this->privates['.service_locator.rXrRW6k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'notification' => ['privates', 'App\\Notification\\NotificationContact', 'getNotificationContactService.php', true],
], [
    'notification' => 'App\\Notification\\NotificationContact',
]);
