<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKDHdPJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKDHdPJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKDHdPJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKDHdPJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWKDHdPJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WKDHdPJ',
    'container.build_id' => '247603c1',
    'container.build_time' => 1568230466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKDHdPJ');
